version: '3'
services:
  vprodb:
    image: ajaytekam/vprofiledb:V1
    build: 
      context: ./Docker-files/db
      dockerfile: Dockerfile
    ports:
    - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vprocache01:
    image: memcached
    ports:
      - "11211:11211"

  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vproapp:
    image: ajaytekam/vprofileapp:V1
    build: 
      context: ./Docker-files/app
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps
    depends_on:
      - vprodb

  vproweb: 
    image: ajaytekam/vprofileweb:V1
    build: 
      context: ./Docker-files/web
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"

volumes:
  vprodbdata: {}
  vproappdata: {}
